### ISSUE TITLE
Chrome marks tonkeygen for MAC as dangerous file

### ISSUE THREAD

**Issue by Kylmakalle** [ton-blockchain/tonkeygen#1]
Affects only Mac OS version using Mac OS Chrome, Using Safari is Fine
10.14.6 Chrome 77.0.3865.90
![image](https://user-images.githubusercontent.com/24507532/66081302-67ad0180-e570-11e9-8671-68515598da7f.png)

Using Windows is fine too
![image](https://user-images.githubusercontent.com/24507532/66081360-88755700-e570-11e9-97bd-1e38b22b4151.png)

_May be unrelated, sorry_

**Comment by john-preston** [comment]
I have no idea, why this happens. I've re-packed it as .dmg setup, it doesn't mark it dangerous for now, I hope it stays that way. Please try downloading it.

**Comment by Kylmakalle** [comment]
@john-preston Now it's fine both Chrome and Safari, good job.
![image](https://user-images.githubusercontent.com/24507532/66115975-9bbd0c80-e5da-11e9-8db5-16dfa6150007.png)
