### ISSUE TITLE
Why mnemonic from tonkeygen can't be imported to any mnemonic tool?

### ISSUE THREAD

**Issue by APshenkin** [ton-blockchain/tonkeygen#2]
Hi!

Tried to enter valid mnemonic to tonkeygen and tonkeygen mnemonic to external tool.

In both cases tools say that mnemonic is invalid (seems like some checksum is not correct)

Ton mnemonics have different generation flow? not BIP39?

If so, why you don't use default BIP39 and what is the difference.

Thanks in advance!

**Comment by APshenkin** [comment]
Explanation is here https://github.com/ton-blockchain/ton/issues/22#issuecomment-538494783

**Comment by evd0kim** [comment]
Are you sure code from ton-blockchain really used in Keygen?

**Comment by APshenkin** [comment]
Yes, it's added via submodule `lib_ton`

https://github.com/desktop-app/lib_ton/blob/b6ca29e3da4e53b35340ba5a9dd935ac8727d125/ton/ton_utility.cpp#L291

**Comment by evd0kim** [comment]
@APshenkin Thanks. Just realized how it could work.
